//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPIModals.AgentRegistration1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int AgentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string AgentPassword { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Agent_Address { get; set; }
        public string Zipcode { get; set; }
    }
}
