//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoopenAPIModals.Account.AdminRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRegister
    {
        public byte AdminId { get; set; }
        public byte[] FirstName { get; set; }
        public byte[] LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long PhoneNumber { get; set; }
        public string ZipCode { get; set; }
        public Nullable<byte> CountryId { get; set; }
        public Nullable<byte> CityId { get; set; }
        public Nullable<byte> StateId { get; set; }
    }
}
